# Makefile 

make: ejercicio_1.cc
	g++ -std=c++11 ejercicio_1.cc -o ejercicio_1

2: ejercicio_2.cc
	g++ -std=c++11 ejercicio_2.cc -o ejercicio_2

3: ejercicio_3.cc
	g++ -std=c++11 ejercicio_3.cc -o ejercicio_3

4: ejercicio_4.cc
	g++ -std=c++11 ejercicio_4.cc -o ejercicio_4

ordenacion: metodos_ordenacion.cc
	g++ -std=c++11 metodos_ordenacion.cc -o ordenacion	

busqueda: ejercicios_busqueda.cc
	g++ -std=c++11 ejercicios_busqueda.cc -o busqueda	