# Makefile 

make: include/sort_algorithm.h include/sort_heapsort.h include/sort_quicksort.h include/sort_radixsort.h include/sort_shellsort.h include/sort.h src/main.cc
	g++ -D DEBUG -std=c++11 src/main.cc -o sort

clean:
	rm -f .out sort	