# Makefile 

make:  include/block.h include/dispersion_function.h include/exploration_function.h include/fd_module.h include/fe_lineal.h include/hash_table.h include/list.h include/sequence.h src/main.cc
	g++ -std=c++11 src/main.cc -o hash_table 

clean:
	rm -f .out hash_table	